swagger: "2.0"
info:
  description: "Node.js implementation of emojivoto with gifs instead of emojis"
  version: "1.0.0"
  title: "nodevoto"
  termsOfService: ""
  contact:
    email: "sebastiantiedtke@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/api"
schemes:
- "http"
paths:
  /leaderboard:
    get:
      tags:
      - "nodevoto"
      summary: Get leaderboard
      description: Returns list of gif in descending order.
      produces:
      - "application/json"
      responses:
        200:
          description: Ordered list of gif
          schema:
            type: array
            items:
              required:
                - shortcode
                - url
                - votes
              properties:
                shortcode:
                  type: string
                url:
                  type: string
                votes:
                  type: integer 
  /vote:
    get:
      tags:
      - "nodevoto"
      summary: "Cast vote for specific gif"
      description: "Cast vote for gif based on choice parameter provided"
      produces:
      - "application/json"
      parameters:
      - name: "choice"
        in: "query"
        description: "Shortcode of specific gif to cast vote for"
        required: true
        type: "string"
        enum: [":1027kiisfm-finger-gun-wango-tango-3oKIPc4QtWXUNlfHpe:",":Bad-Pug-pug-pugs-ahahah-tJOxsPuexkX4BNHcjx:",":RobertEBlackmon-homer-simpson-wtf-7N8To79F9ny8Yfdnro:",":RosannaPansino-dog-hello-SHOnbgVOjmI4q6n0Gz:",":afv-l41lFeGts4W1gbKCc:",":airplane-i-am-serious-surely-you-cant-be-3oEjHLzm4BCF8zfPy0:",":alroker-al-roker-3ohzdFhIALkXTBxPkQ:",":angry-monday-working-xiAqCzbB3eZvG:",":animation-lol-l44QmLrXyMhztpB28:",":art-cute-okay-3oxHQjb3brk6dOWBGg:",":bestfriends-3ohhwhGY6WXtejX86k:",":bestfriends-cat-reaction-2wgWuwZoxUT8ZJy9rs:",":bigbrotherca-wtf-what-1Q6yzrOnjDqTK:",":bojackhorseman-3o7aD289PT63bP0p0c:",":cat-goodbye-done-iPiUxztIL4Sl2:",":cat-kitten-sleep-lck0BfsWrHeFUU63u1:",":cat-office-working-xUA7aVAw3xQ4pzYkiA:",":cbs-cheers-ncis-los-angeles-3oKIPxK3KICQsFRs4M:",":chescaleigh-9Prt3R3uE3QdCotmx9:",":comedycentral-workaholics-smile-l0Iyh6fhBXWBt3kU8:",":dance-beyonce-RX7N03MEUafW8:",":dance-dancing-funny-l4JyOrGkMIwwGFvOg:",":david-hasselhoff-funny-crazy-jAF3mI0ja5hUk:",":dog-smile-work-xULW8FW2AcOtYCj4qs:",":facethetruthtv-A5SyfVgTsOrzW8TPI6:",":foxsearchlight-super-troopers-jay-chandrasekhar-1xo9BMTCjcKa6BnQsO:",":funny-gif-artist-g-u0aCCHXiIOXA9fHOEB:",":funny-smile-text-mWVuNFR8CVguA:",":garfield-cat-coffee-pzryvxGeykOxeC0fWb:",":gotham-foxtv-fox-broadcasting-3oKIPlAKUjRpoc3duw:",":hallmarkmovie-the-disappearing-game-aurora-teagarden-mysteries-8UHRkgHJJwMpDsercS:",":happy-excited-yes-3o752oaxOmmOUEvBCM:",":happy-fun-excited-5Szx4RRo8hFcU4lwfD:",":heyviolet-3o7btWyOD1QLDZGqly:",":hyperrpg-twitch-hyper-rpg-vcqhLPFLwsaWCOOEdk:",":jaydenbartels-jayden-bartels-5QLy2hJlQAsrm7ycdq:",":jimgaffigan-jim-gaffigan-4a9Tlz3Mj2LS5LMw33:",":justviralnet-funny-kid-5ZZSYqvcH6QppFQGI5:",":kawaii-dumpster-fire-1wXeLxuTVBZe0Ht7Zu:",":lego-l4q7VhGsL6BnXJrc4:",":lildicky-lil-dicky-26FmS0Hh04k0zC9R6:",":love-art-cute-l0HU2sYgCZh3HiKnS:",":love-cute-girl-YjF2enuCvcmDGoPiW9:",":love-kiss-heart-xUOwGeHJEQ46pdsvWE:",":mlb-fan-royals-dances-3dpU8296xMImdZwGx3:",":molangofficialpage-sad-tired-bummer-2bUmRLilhMNzHoSMPd:",":morning-good-vibes-3rSPmDt4h1WS7c2KgA:",":mostexpensivest-viceland-2-chainz-most-expensivest-oFRWQb3IDMcrge97mV:",":musicchoice-cute-excited-3og0IPacuEoA6BBTUI:",":musicchoice-dinah-jane-dinahjane-60rGCYzybV3uKSiPRR:",":natgeowild-pupparazzi-puppy-potty-face-uVj98vsKTb1lDRC4Hz:",":nehumanesociety-cat-cats-l4pTcCSqMck62swFi:",":netflix-dinosaur-cupcake-cupcakedino-vND72IouxKfcW6BlW2:",":new-girl-new-girl-jess-day-newgirl-l4HofcnCafWVp7z9e:",":next-pFwRzOLfuGHok:",":nfl-258Am8OQ9QoL7miuN8:",":nfl-smith-trequan-tre-quan-OkjN1aAB7z7njXRLdr:",":oscars-academy-awards-1997-l0Exg7sYYOUPDeUiA:",":oxygenmedia-side-eye-no-you-didnt-deitrick-haddon-TlK63EGn8YyRbiI6mBy:",":pokemon-school-college-rAm0u2k17rM3e:",":reaction-aretha-franklin-oywxRdE6LDBESF4JbC:",":reaction-mood-PO6fwUFlxcFF9ojkPQ:",":rtl5-rtl-5-hntm-hollands-next-top-model-3gOKitIckaTTDkuc74:",":sandiegozoo-mv2Txel3lmlA2tjlch:",":siliconvalleyhbo-hbo-tech-xUA7bjoUNhwWVCfTR6:",":sjearthquakes-mls-san-jose-earthquakes-quakes-5pYrisHa1ai017EwbE:",":sloth-sloths-slothilda-3o6gaVztoohCD4cdAk:",":spongebob-cartoon-nickelodeon-thumbs-3o7absbD7PbTFQa0c8:",":studiosoriginals-valentines-day-happy-l3q2LJoEChm4UE7FS:",":studiosoriginals-xT9IgOdxEm8gYoJblC:",":swizzbeatz-poison-swizz-beatz-pistol-on-my-side-dtCsOJshjPfiUyKJ2x:",":sza-l4FGDxbJmDwZhPaPC:",":teamcoco-httptoteamcococom2znbupz-3ov9k7AbzUYmckXSQE:",":thanks-thankyou-omerismos-jTHaR5a3B5L3jND7fP:",":the-x-files-3oEduLGIEoZHNJ9CUM:",":thebachelorette-dance-kiss-NRtOdMpKvFDdu4O3Yp:",":thephizzogs-l3q2VIWn4W0z1rfos:",":thisisgiphy-reaction-audience-3o7qDPfGhunRMZikI8:",":tommywiseau-football-super-bowl-xUOwGb60WL1S0SEZEY:",":universityofkansas-cool-sunglasses-26BGG0Vj4nulivlO8:",":ussoccer-funny-lol-95Euu3wrLljyg:",":vhs-positive-vhspositive-3o7qE4opCd6f1NJeuY:",":whatthefashion-love-yes-yas-fxz3b4oPaZs28sMNIf:",":win-winner-robdougie-8mdWuyUbqcOacqNWmJ:",":yes-100-agree-xUOwGjPHOGcv9ddpYc:"]
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
        400:
          description: "Choosen gif shortcode doesnt exist"
        500:
          description: "Unknown Error"
  /list:
    get:
      tags:
      - "nodevoto"
      summary: "Fetch all gif supported"
      description: "Returns list of all gif supported on the ballot"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: array
            items:
              required:
                - url
                - shortcode
              properties:
                url:
                  type: string
                shortcode:
                  type: string
        500:
          description: "Unknown Error"
